{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0",
    "title": "API Documentation | Printful",
    "description": "# About the Printful API\n\nThe Printful API is a RESTful API, that uses an HTTP protocol for communication. HTTP GET, POST, PUT and DELETE methods are used to access the API resources.\n\n## Postman Collection\n\nYou can explore the API using the Postman collection:\n\n<a href=\"postman/printful_postman_collection.json\" download>Download Postman Collection</a>\n\n## Requests and responses\n\n### Request endpoint\nAll API requests have to be sent to this URL:\n```\nhttps://a[...]",
    "contact": {
      "name": "Printful developer support",
      "url": "https://developers.printful.com/docs/#tag/Other-resources/Developer-support"
    },
    "x-logo": {
      "url": "https://static.cdn.printful.com/dist-pf/image-assets/off-center-full-color-black.1de1e822b15b8e74075c8d1fa631d4e3.svg",
      "backgroundColor": "#FFFFFF",
      "altText": "Printful"
    }
  },
  "servers": [
    {
      "url": "https://api.printful.com",
      "description": "The Printful API is a RESTful API, that uses the HTTP protocol for communication. HTTP GET, POST, PUT and DELETE methods are used to access the API."
    }
  ],
  "tags": [
    {
      "name": "Localisation",
      "description": "Some of the resources returned by the API are translated into several languages. By default, they are returned in\nEnglish in the API responses.\n\nIf you want to get a response with texts in another language, you can use the `X-PF-Language`\nHTTP header. Its value should be the long version of the locale to use (e.g. `es_ES` for Spanish).\nPossible localisation parameters:\n- en_US\n- en_GB\n- en_CA\n- es_ES\n- fr_FR\n- de_DE\n- it_IT\n- ja_JP\n\n### Example\n\nProduct det[...]"
    },
    {
      "name": "Authorization",
      "description": "### Private tokens and public apps\nThere are two different ways of using Printful OAuth - **Private token** and **Public App**. If you are developing an API solution for your personal store, you should choose ***Private Token***. But if you are building an Public App that will be used by a wider audience, you should be choosing **Public App**.\n\n### Client types\nThere are two different client types - **Store** and **Account**. Store access level client is only able to ac[...]"
    },
    {
      "name": "Public App authorization",
      "description": "#### Public App installation flow\nPublic App installation starts with a user redirection to an app-specific installation URL. Installation URL has to be\ngenerated in the following format:\n\n`https://www.printful.com/oauth/authorize?client_id={clientId}&state={stateValue}&redirect_url={redirectUrl}`\n\n| Parameter    | Description                                                                                                    |\n|--------------|-------------------------[...]"
    },
    {
      "name": "OAuth API",
      "description": "OAuth API allows receiving data for token"
    },
    {
      "name": "Catalog API",
      "description": "Printful has a substantial catalog of blank Products and Variants. A Product can describe a specific type, model and manufacturer of the item, while the Variant specifies the more detailed attributes of the product like the exact size/color of a\nT-shirt or the dimensions of a poster. Moreover, each item in the Printful Catalog has a unique Variant ID. When managing Sync Products or orders, you will need to specify the Variant ID of the specific blank item, hence you can us[...]"
    },
    {
      "name": "Products API",
      "description": "**The Products API resource lets you create, modify and delete products in a Printful store based on the Manual orders /\nAPI platform** (you can create such store by going to the Stores section at your Printful dashboard.)\n\n**Important**: Jewelry products are not supported via API.\n\n<div class=\"alert alert-info\" style=\"word-wrap: break-word; padding: 16px; border-radius: 0; cursor: default; color: #31708f; background-color: #d9edf7; border-color: #bce8f1;\">\nTo con[...]"
    },
    {
      "name": "Product Templates API",
      "description": "The Product Templates API resource lets you retrieve the product templates information.\n\n### External Product ID\n\nIn case of a single template retrieval it is possible to get it by the External Product ID. In order to do this, the ID needs to be prepended with the '@' character. Here are the examples of how to get the template data by the Template ID and by the External Product ID.\n\n```\nGET /product-templates/11001  - reference by Printful Template ID\nGET /product-t[...]"
    },
    {
      "name": "Orders API",
      "description": "The Orders API is the most important part of the Printful API - it allows you to create new orders and confirm them for\nfulfillment.\n\n**Important**: Jewelry products are not supported via API.\n\n### Order life cycle and statuses\n\nEach order will go through different states while being processed. The following order status types indicate those\nstates:\n\n<table>\n    <tr>\n        <td><strong>draft</strong></td>\n        <td>The order is created but is not yet submitt[...]"
    },
    {
      "name": "File Library API",
      "description": "To avoid the need to upload every file again when the same item is ordered,\nyour print files are stored in the File Library and can be reused.\n\nYou can use this API to directly add files to the library, and later use\nFile IDs when creating orders. However, the more convenient way is to specify\nthe files by URL at the same time the order is created.\n\n<div class=\"alert alert-info\">\nMost probably you will never need to use this API - just specify the file URL\nwhen c[...]"
    },
    {
      "name": "Shipping Rate API",
      "description": "The Shipping rate API calculates the shipping rates for an order based on the recipient's location and the contents of\nthe order.\n\nThe returned shipping rate ID can be used to specify the shipping method when creating an order.\n\nSee [Country/State Code API](#tag/CountryState-Code-API) for information about the Country codes.\n\nSee [Catalog API](#tag/Catalog-API) for information about the Variant IDs.\n\n<div class=\"alert alert-info\">\n<p><strong>Note:</strong> The s[...]"
    },
    {
      "name": "Ecommerce Platform Sync API",
      "description": "The ecommerce platform sync API allows you to automatically assign Printful\nproducts and print files to the products in your online store (Shopify, Woocommerce, etc.)\nthat is linked to Printful.\n\n### Sync Products & Sync Variants explained\n\nEach product in your store can contain one or multiple variants\n(some ecommerce platforms would call these options) that the customer can purchase\n(imagine multiple sizes or colors of the same t-shirt design). When you link your\[...]"
    },
    {
      "name": "Country/State Code API",
      "description": "To create an order, you have to use country and state codes to specify the recipient address. Both country code and state code are mandatory for orders to the USA, Canada and Australia. For other countries only the country code is needed to create an order.\n\nCountry codes are based on the ISO 3166-1 alpha-2 standard and are two letters long.\n\nState codes are based on the ISO 3166-2 standard by omitting the country code part of the code and are used only for the USA, Can[...]"
    },
    {
      "name": "Tax Rate API",
      "description": " "
    },
    {
      "name": "Webhook API",
      "description": "Webhooks are an API feature that allows your system to receive notifications about certain events.\n\nWhen an event occurs, the Printful server ([Webhook Simulator](https://www.printful.com/api/webhook-simulator))\nwill make a POST request to your defined\nURL that will contain a JSON object in the request body.\nYour server has to respond with HTTP status `2xx OK`,\notherwise, the request will be retried in increasing intervals\n(after 1, 4, 16, 64, 256 and 1024 minutes).\[...]"
    },
    {
      "name": "Store Information API",
      "description": " "
    },
    {
      "name": "Mockup Generator API",
      "description": "To generate mockups, first, you need to decide on which products you want them. API methods on retrieving products and\nvariants can be found in the [Catalog API](#tag/Catalog-API).\n\n**Note**: Remember to distinguish the difference between a product id and a variant id. Some API endpoints require an id\nfrom a variant and some from a product.\n\n**Important**: Jewelry products are not supported via API.\n\n### Print files\n\nA print file defines resolution which should be[...]"
    },
    {
      "name": "Warehouse Products API",
      "description": "Warehouse Products API"
    },
    {
      "name": "Reports API",
      "description": "The Reports API lets you retrieve reports like the statistics related to the orders fulfilled for your stores.\n"
    },
    {
      "name": "Approval Sheets API",
      "description": "Approval Sheets API"
    },
    {
      "name": "Common",
      "description": "# Options\nOptions allow for additional modification of how product will look.\n\n<details>\n    <summary>List of currently available thread color options</summary>\n\n| <div style=\"width:320px\">Option</div> | <div style=\"width:250px\">Placement</div> | Description                                               |\n|---------------------------------------|------------------------------------------|-----------------------------------------------------------|\n| `thread_colo[...]"
    },
    {
      "name": "Other resources",
      "description": "## Developer support\n\nThe previous dedicated developer support channel is not currently monitored.\n\nWith all questions, including ones related to our API, please contact our Customer Support\nat [https://www.printful.com/contacts](https://www.printful.com/contacts).\n\n## Bug reporting\n\nTo report a potential security vulnerability, please send a detailed email to the contacts\ndescribed in our [security.txt](https://printful.com/.well-known/security.txt) file.\n\nTo h[...]"
    },
    {
      "name": "Basic use cases",
      "description": "# Basic use cases\n\nAll the API integrations begin with a decision on how to authenticate with the Printful API. The most common use cases for Printful API integrations are:\n\n<pre class=\"mermaid\">\n    graph TD\n    A[Authentication Methods] --> B[Private API Token]\n    A --> C[Public App OAuth]\n    B --> D[Single Printful Account]\n    C --> G[Single Printful Account of Marketplace Owner]\n    G --> E[Multiple Printful Accounts]\n    E --> H[Merchant 1]\n    E --> I[...]"
    },
    {
      "name": "Tutorials",
      "description": "## Make your first order through the API\n\n### API Flow Overview\n\nHere's a quick visual overview of how your system communicates with Printful's API during the order creation flow:\n\n![Authentication setup](images/tutorial/api-integration/authentication_setup.png)\n![OAuth integration flow](images/tutorial/api-integration/oauth_integration.png)\n![Order creation and fulfillment](images/tutorial/api-integration/order_creation.png)\n![Webhook handling](images/tutorial/api[...]"
    },
    {
      "name": "Errors",
      "description": "# General errors\n\n| <div style=\"width:60px; \">Code</div> | <div style=\"width:250px;\">Name</div> | Explanation                                                                                                 |\n|:------------------------------------:|:-------------------------------------|:------------------------------------------------------------------------------------------------------------|\n|                 401                  | `UNAUTHORIZED`                 [...]"
    },
    {
      "name": "Examples",
      "description": "# Catalog API examples\n\n### API Flow Overview\n\nHere's a quick visual overview of how your system communicates with Printful's API during the order creation flow:\n\n![Authentication setup](images/tutorial/api-integration/authentication_setup.png)\n![OAuth integration flow](images/tutorial/api-integration/oauth_integration.png)\n![Order creation and fulfillment](images/tutorial/api-integration/order_creation.png)\n![Webhook handling](images/tutorial/api-integration/produ[...]"
    }
  ],
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "Catalog API"
        ],
        "summary": "Get Products",
        "description": "Returns list of Products available in the Printful",
        "operationId": "getProducts"
      }
    },
    "/products/variant/{id}": {
      "get": {
        "summary": "Get Variant",
        "description": "Returns information about a specific Variant and its Product",
        "operationId": "getVariantById",
        "tags": [
          "Catalog API"
        ]
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "Get Product",
        "description": "Returns information about a specific product and a list of variants for this product.",
        "operationId": "getProductById",
        "tags": [
          "Catalog API"
        ]
      }
    },
    "/products/{id}/sizes": {
      "get": {
        "summary": "Get Product Size Guide",
        "description": "Returns information about the size guide for a specific product.",
        "operationId": "getProductSizeGuideById",
        "tags": [
          "Catalog API"
        ]
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Catalog API"
        ],
        "summary": "Get Categories",
        "description": "Returns list of Catalog Categories available in the Printful",
        "operationId": "getCategories"
      }
    },
    "/categories/{id}": {
      "get": {
        "summary": "Get Category",
        "description": "Returns information about a specific category.",
        "operationId": "getCategoryById",
        "tags": [
          "Catalog API"
        ]
      }
    },
    "/store/products": {
      "get": {
        "summary": "Get Sync Products",
        "description": "Returns a list of Sync Product objects from your custom Printful store.",
        "operationId": "getSyncProducts",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      },
      "post": {
        "summary": "Create a new Sync Product",
        "description": "Creates a new Sync Product together with its Sync Variants ([See examples](#tag/Products-API/operation/createSyncProduct)).",
        "operationId": "createSyncProduct",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      }
    },
    "/store/products/{id}": {
      "get": {
        "summary": "Get a Sync Product",
        "description": "Get information about a single Sync Product and its Sync Variants.",
        "operationId": "getSyncProductById",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      },
      "delete": {
        "summary": "Delete a Sync Product",
        "description": "Deletes a Sync Product with all of its Sync Variants",
        "operationId": "deleteSyncProduct",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      },
      "put": {
        "summary": "Modify a Sync Product",
        "description": "Modifies an existing Sync Product with its Sync Variants.\n\nPlease note that in the request body you only need to specify the fields that need to be changed. Furthermore, if you want to update existing sync variants, \nthen in the sync variants array you must specify the IDs of all existing sync variants. All omitted existing sync variants will be deleted. All new sync \nvariants without an ID will be created. See examples for more insights.\n\n**Rate limiting:** Up to 1[...]",
        "operationId": "updateSyncProduct",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      }
    },
    "/store/variants/{id}": {
      "get": {
        "summary": "Get a Sync Variant",
        "description": "Get information about a single Sync Variant.",
        "operationId": "getSyncVariantById",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      },
      "delete": {
        "summary": "Delete a Sync Variant",
        "description": "Deletes a single Sync Variant.",
        "operationId": "deleteSyncVariant",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      },
      "put": {
        "summary": "Modify a Sync Variant",
        "description": "Modifies an existing Sync Variant.\n\nPlease note that in the request body you only need to specify the fields that need to be changed. See examples for more insights.\n\n[See examples](#tag/Examples/Products-API-examples/Modify-a-Sync-Variant)\n",
        "operationId": "updateSyncVariant",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      }
    },
    "/store/products/{id}/variants": {
      "post": {
        "summary": "Create a new Sync Variant",
        "description": "Creates a new Sync Variant for an existing Sync Product ([See examples](#tag/Examples/Products-API-examples/Create-a-new-Sync-Variant)).",
        "operationId": "createSyncVariant",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Products API"
        ]
      }
    },
    "/product-templates": {
      "get": {
        "summary": "Get product template list",
        "description": "Returns a list of templates.",
        "operationId": "getProductTemplates",
        "security": [
          {
            "OAuth": [
              "product_templates/read"
            ]
          }
        ],
        "tags": [
          "Product Templates API"
        ]
      }
    },
    "/product-templates/{id}": {
      "get": {
        "summary": "Get product template",
        "description": "Get information about a single product template",
        "operationId": "getProductTemplateById",
        "security": [
          {
            "OAuth": [
              "product_templates/read"
            ]
          }
        ],
        "tags": [
          "Product Templates API"
        ]
      },
      "delete": {
        "summary": "Delete product template",
        "description": "Delete product template by ID or External Product ID",
        "operationId": "deleteProductTemplate",
        "security": [
          {
            "OAuth": [
              "product_templates"
            ]
          }
        ],
        "tags": [
          "Product Templates API"
        ]
      }
    },
    "/orders": {
      "get": {
        "summary": "Get list of orders",
        "description": "Returns list of order objects from your store",
        "operationId": "getOrders",
        "security": [
          {
            "OAuth": [
              "orders/read"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      },
      "post": {
        "summary": "Create a new order",
        "description": "Creates a new order and optionally submits it for fulfillment ([See examples](#tag/Examples/Orders-API-examples))",
        "operationId": "createOrder",
        "security": [
          {
            "OAuth": [
              "orders"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      }
    },
    "/orders/{id}": {
      "get": {
        "summary": "Get order data",
        "description": "Returns order data by ID or External ID.",
        "operationId": "getOrderById",
        "security": [
          {
            "OAuth": [
              "orders/read"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      },
      "delete": {
        "summary": "Cancel an order",
        "description": "Cancels pending order or draft. Charged amount is returned to the store owner's credit card.",
        "operationId": "cancelOrderById",
        "security": [
          {
            "OAuth": [
              "orders"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      },
      "put": {
        "summary": "Update order data",
        "description": " Updates unsubmitted order and optionally submits it for the fulfillment.\n\n Note that you need to post only the fields that need to be changed, not all required fields.\n\n If items array is given in the update data, the items will be:\n\n a) updated, if the update data contains the item id or external_id parameter that alreay exists\n\n b) deleted, if the request doesn't contain the item with previously existing id\n\n c) created as new if the id is not given or does n[...]",
        "operationId": "updateOrderById",
        "security": [
          {
            "OAuth": [
              "orders"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      }
    },
    "/orders/{id}/confirm": {
      "post": {
        "summary": "Confirm draft for fulfillment",
        "description": "Approves for fulfillment an order that was saved as a draft. Store owner's credit card is charged when the order is submitted for fulfillment.",
        "operationId": "confirmOrderById",
        "security": [
          {
            "OAuth": [
              "orders"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      }
    },
    "/orders/estimate-costs": {
      "post": {
        "summary": "Estimate order costs",
        "description": "Calculates the estimated order costs including item costs, print costs (back prints, inside labels etc.), shipping and taxes",
        "operationId": "estimateOrderCosts",
        "security": [
          {
            "OAuth": [
              "orders/read"
            ]
          }
        ],
        "tags": [
          "Orders API"
        ]
      }
    },
    "/files": {
      "post": {
        "summary": "Add a new file",
        "description": "Adds a new File to the library by providing URL of the file.\n\nIf a file with identical URL already exists, then the original file is returned. If a file does not exist, a new file is created.\n\n[See examples](#tag/Examples/File-Library-API-examples/Add-a-new-file)\n",
        "operationId": "addFile",
        "security": [
          {
            "OAuth": [
              "file_library"
            ]
          }
        ],
        "tags": [
          "File Library API"
        ]
      }
    },
    "/files/{id}": {
      "get": {
        "summary": "Get file",
        "description": "Returns information about the given file.",
        "operationId": "getFile",
        "security": [
          {
            "OAuth": [
              "file_library/read"
            ]
          }
        ],
        "tags": [
          "File Library API"
        ]
      }
    },
    "/files/thread-colors": {
      "post": {
        "summary": "Return available thread colors from provided image URL",
        "description": "Returns colors in hexadecimal format.\n\nReturned thread colors are matched as closely as possible to provided image colors.\n\n[See examples](#tag/Examples/File-Library-API-examples/Suggest-thread-colors)\n",
        "operationId": "threadColors",
        "tags": [
          "File Library API"
        ]
      }
    },
    "/sync/products": {
      "get": {
        "summary": "Get list of Sync Products",
        "description": "Returns list of Sync Product objects from your store.",
        "operationId": "getStoreSyncProducts",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      }
    },
    "/sync/products/{id}": {
      "get": {
        "summary": "Get a Sync Product",
        "description": "Get information about a single Sync Product and its Sync Variants",
        "operationId": "getStoreSyncProductById",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      },
      "delete": {
        "summary": "Delete a Sync Product",
        "description": "Deletes a Sync Product with all of its Sync Variants",
        "operationId": "deleteStoreSyncProduct",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      }
    },
    "/sync/variant/{id}": {
      "get": {
        "summary": "Get a Sync Variant",
        "description": "Get information about a single Sync Variant",
        "operationId": "getStoreSyncVariantById",
        "security": [
          {
            "OAuth": [
              "sync_products/read"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      },
      "put": {
        "summary": "Modify a Sync Variant",
        "description": "Modifies an existing Sync Variant.\n\nPlease note that in the request body you only need to specify the fields that need to be changed. See examples for more insights.\n\n **Rate limiting:** Up to 10 requests per 60 seconds. A 60 seconds lockout is applied if request count is exceeded.\n\n[See examples](#tag/Examples/Ecommerce-Platform-Sync-API-examples/Modify-a-Sync-Variant)\n",
        "operationId": "updateStoreSyncVariant",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      },
      "delete": {
        "summary": "Delete a Sync Variant",
        "description": "Deletes configuraton information (`variant_id`, print files and options) and disables automatic order importing for this Sync Variant.",
        "operationId": "deleteStoreSyncVariant",
        "security": [
          {
            "OAuth": [
              "sync_products"
            ]
          }
        ],
        "tags": [
          "Ecommerce Platform Sync API"
        ]
      }
    },
    "/shipping/rates": {
      "post": {
        "summary": "Calculate shipping rates",
        "description": "Returns available shipping options and rates for the given list of products.\n\n**Recipient Address Requirements:**\n- Only `country_code` is required in the recipient object\n- `state_code` is only required for United States (US), Australia (AU), and Canada (CA)\n- All other recipient fields are optional\n\n**Note:** Providing more address information may produce more precise results and more shipping options. While only the country code is required, including additional[...]",
        "operationId": "calculateShippingRates",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Shipping Rate API"
        ]
      }
    },
    "/countries": {
      "get": {
        "summary": "Retrieve country list",
        "description": "Returns list of countries and states that are accepted by the Printful.",
        "operationId": "getCountries",
        "tags": [
          "Country/State Code API"
        ]
      }
    },
    "/tax/countries": {
      "get": {
        "summary": "Get a list of countries for tax calculation",
        "description": "Retrieve state list that requires sales tax calculation",
        "operationId": "getTaxCountries",
        "tags": [
          "Tax Rate API"
        ]
      }
    },
    "/tax/rates": {
      "post": {
        "summary": "Calculate tax rate",
        "description": "Calculates sales tax rate for given address if required.\n\n<div class=\"alert alert-info\">\n  ⚠️ <strong>Important – <tt>/tax/rates</tt> endpoint sunset</strong>\n  <p>Since May 2023, the POST <tt>/tax/rates</tt> endpoint is no longer maintained and may return inaccurate results.</p>\n  <p>On <strong>July 29, 2025</strong>, we started the sunset process. The rate limit is being reduced by 10 RPM each week (starting with 60) until it reaches 0 on <strong>September 8, 202[...]",
        "operationId": "calculateTaxRates",
        "deprecated": true,
        "tags": [
          "Tax Rate API"
        ]
      }
    },
    "/store/packing-slip": {
      "post": {
        "summary": "Change packing slip",
        "description": "Modifies packing slip information of the currently authorized Printful store.",
        "operationId": "changePackingSlip",
        "security": [
          {
            "OAuth": [
              "stores_list"
            ]
          }
        ],
        "tags": [
          "Store Information API"
        ]
      }
    },
    "/stores": {
      "get": {
        "summary": "Get basic information about stores",
        "description": "Get basic information about stores depending on the token access level",
        "operationId": "getStores",
        "security": [
          {
            "OAuth": [
              "stores_list"
            ]
          }
        ],
        "tags": [
          "Store Information API"
        ]
      }
    },
    "/stores/{id}": {
      "get": {
        "summary": "Get basic information about a store",
        "description": "Get basic information about a store based on provided ID",
        "operationId": "getStore",
        "security": [
          {
            "OAuth": [
              "stores_list"
            ]
          }
        ],
        "tags": [
          "Store Information API"
        ]
      }
    },
    "/mockup-generator/create-task/{id}": {
      "post": {
        "summary": "Create a mockup generation task",
        "description": "Creates an asynchronous mockup generation task.\nGeneration result can be retrieved using mockup generation task retrieval endpoint.<br>\n**Rate limiting**: Up to 10 requests per 60 seconds for established stores;\n2 requests per 60 seconds for new stores. Currently available rate is returned in response headers.\nA 60 seconds lockout is applied if request count is exceeded. We also limit the number of files that may\nbe generated to 20,000 files per account in a 24-hour [...]",
        "operationId": "createGeneratorTask",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Mockup Generator API"
        ]
      }
    },
    "/mockup-generator/printfiles/{id}": {
      "get": {
        "summary": "Retrieve product variant printfiles",
        "description": "List of printfiles available for products variants. Printfile indicates what file resolution should be used to create a mockup or submit an order.\n\n<div class=\"alert alert-info\">\nThis endpoint uses DTG as a default printing technique for products\nwith more than one technique available. For products with DTG and more\ntechniques available please specify the correct technique in query by using\nthe `technique` parameter. For more information read the <a href=\"#tag/Ex[...]",
        "operationId": "getPrintfiles",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Mockup Generator API"
        ]
      }
    },
    "/mockup-generator/task": {
      "get": {
        "summary": "Mockup generation task result",
        "description": "Returns asynchronous mockup generation task result. If generation task is completed, it will contain a list of generated mockups.",
        "operationId": "getTask",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Mockup Generator API"
        ]
      }
    },
    "/mockup-generator/templates/{id}": {
      "get": {
        "summary": "Layout templates",
        "description": "Retrieve list of templates that can be used for client-side positioning.\n\n<div class=\"alert alert-info\">\nThis endpoint uses DTG as a default printing technique for product layouts\nwith more than one technique available. For products with DTG and more\ntechniques available please specify the correct technique in query by using\nthe `technique` parameter. For more information read the <a href=\"#tag/Examples/Mockup-Generator-API-examples\">examples</a>.\n</div>\n",
        "operationId": "getTemplates",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Mockup Generator API"
        ]
      }
    },
    "/warehouse/products": {
      "get": {
        "summary": "Get a list of your warehouse products",
        "description": "Returns a list of warehouse products from your store\n\n<div class=\"alert alert-info\">\n  The response for this endpoint was documented as paginated, although it was not paginated. The behavior will be \n  fixed and the paginated result will be set as the default. Currently to get paginated results please send\n  <code>true</code>or <code>1</code> in <code>X-PF-Force-Pagination</code> header. \n</div>\n",
        "operationId": "getWarehouseProducts",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Warehouse Products API"
        ]
      }
    },
    "/warehouse/products/{id}": {
      "get": {
        "summary": "Get warehouse product data",
        "description": "Returns warehouse product data by ID",
        "operationId": "getWarehouseProduct",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Warehouse Products API"
        ]
      }
    },
    "/approval-sheets": {
      "get": {
        "summary": "Retrieve a list of approval sheets",
        "description": "Retrieve a list of approval sheets confirming suggested changes to files of on hold orders.",
        "operationId": "getApprovalSheets",
        "tags": [
          "Approval Sheets API"
        ]
      },
      "post": {
        "summary": "Approve a design",
        "description": "Uses the confirm hash of an approval sheet to approve a design and remove the hold on an order",
        "operationId": "approveDesign",
        "tags": [
          "Approval Sheets API"
        ]
      }
    },
    "/approval-sheets/changes": {
      "post": {
        "summary": "Submit changes to an approval sheet",
        "description": "Use this to submit alternative changes to a design that has an approval sheet",
        "operationId": "submitApprovalSheetChanges",
        "tags": [
          "Approval Sheets API"
        ]
      }
    },
    "/webhooks": {
      "get": {
        "summary": "Get webhook configuration",
        "description": "Returns configured webhook URL and list of webhook event types enabled for the store",
        "operationId": "getWebhooks",
        "security": [
          {
            "OAuth": [
              "webhooks"
            ]
          }
        ],
        "tags": [
          "Webhook API"
        ]
      },
      "post": {
        "summary": "Set up webhook configuration",
        "description": "Use this endpoint to enable a webhook URL for a store and select webhook event types that will be sent to this URL.\n\n Note that only one webhook URL can be active for a store, so calling this method disables all existing webhook configuration.\n\n Setting up the [Stock updated](#operation/stockUpdated) webhook requires passing IDs for products that need to be monitored for changes. Stock update webhook will only include information for specified products. These product [...]",
        "operationId": "createWebhook",
        "security": [
          {
            "OAuth": [
              "webhooks"
            ]
          }
        ],
        "tags": [
          "Webhook API"
        ]
      },
      "delete": {
        "summary": "Disable webhook support",
        "description": "Removes the webhook URL and all event types from the store.",
        "operationId": "disableWebhook",
        "security": [
          {
            "OAuth": [
              "webhooks"
            ]
          }
        ],
        "tags": [
          "Webhook API"
        ]
      }
    },
    "/oauth/scopes": {
      "get": {
        "summary": "Get scopes for token",
        "description": "Returns a list of scopes associated with the token",
        "operationId": "getScopes",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "OAuth API"
        ]
      }
    },
    "/reports/statistics": {
      "get": {
        "summary": "Get statistics",
        "description": "Returns statistics for specified report types.\n\nYou need to specify the report types you want to retrieve in the `report_types` query parameter as a comma-separated list,\ne.g. `report_types=sales_and_costs,profit`.\n\n**Note**: You cannot get statistics for a period longer than 6 months.\n\n#### Example\n\nTo get statistics in the default currency of a store for `sales_and_costs` and `profit` reports for August 2022, you can use the\nfollowing\nURL: https://api.printfu[...]",
        "operationId": "getStatistics",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": [
          "Reports API"
        ]
      }
    }
  },
  "x-webhooks": {
    "package_shipped": {
      "post": {
        "summary": "Package shipped",
        "operationId": "packageShipped",
        "description": "Is called when a shipment with all or part of the ordered items is shipped.\n\n If the order is shipped in multiple shipments, this event will be called for every shipment sent.\n\n If some items are reshipped, a shipping notification will be sent again for the same items.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "package_returned": {
      "post": {
        "summary": "Package returned",
        "operationId": "packageReturned",
        "description": " Is called when a shipment is processed as returned to the fulfillment facility. To learn more about the reasons why a shipment might be returned, take a look at [Printful's Return Policy](https://www.printful.com/policies/returns) ",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_created": {
      "post": {
        "summary": "Order created",
        "operationId": "orderCreated",
        "description": "Is called when the order is first created.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_updated": {
      "post": {
        "summary": "Order updated",
        "operationId": "orderUpdated",
        "description": "Is called when an existing order gets updated for any reason - including things that are covered with other webhooks like `order_canceled`.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_failed": {
      "post": {
        "summary": "Order failed",
        "operationId": "orderFailed",
        "description": "Is called when a confirmed order changes its status to `failed`.\n\n It can happen, for example, if printfiles can not be downloaded, are not valid image files or when there is a payment failure.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_canceled": {
      "post": {
        "summary": "Order canceled",
        "operationId": "orderCanceled",
        "description": "Is called when a confirmed order changes its status to `canceled`.\n\n It can happen when a submitted order is canceled from the dashboard or through the API or when the order is canceled by the Printful staff.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "product_synced": {
      "post": {
        "summary": "Product synced",
        "operationId": "productSynced",
        "description": "Is called when a new product or variant is imported from the store's ecommerce integration.\n\n See [Ecommerce Platform Sync API](#tag/Ecommerce-Platform-Sync-API)",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "product_updated": {
      "post": {
        "summary": "Product updated",
        "operationId": "productUpdated",
        "description": "Is called when a new product or variant is created or updated in any way.\n\n See [Ecommerce Platform Sync API](#tag/Ecommerce-Platform-Sync-API)",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "product_deleted": {
      "post": {
        "summary": "Product deleted",
        "operationId": "productDeleted",
        "description": "Is called when a new product or variant is deleted.\n\n See [Ecommerce Platform Sync API](#tag/Ecommerce-Platform-Sync-API)",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "stock_updated": {
      "post": {
        "summary": "Stock updated",
        "operationId": "stockUpdated",
        "description": "Is called when stock is updated for some of a product's variants.\n\n Contains product id and ids of it's discontinued variants and variants that are out of stock. Variant ids that are not present should be considered as active and in stock.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_put_hold": {
      "post": {
        "summary": "Order put hold",
        "operationId": "orderPutHold",
        "description": "Is called when order is put on hold.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_put_hold_approval": {
      "post": {
        "summary": "Order put hold approval",
        "operationId": "orderPutHoldApproval",
        "description": "Is called when order is put on hold and there are changes that must be approved by the customer before fulfillment. Will contain a confirm hash that can be used to approve changes with the Approval Sheets Api.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_remove_hold": {
      "post": {
        "summary": "Order remove hold",
        "operationId": "orderRemoveHold",
        "description": "Is called when order is removed from hold.",
        "tags": [
          "Webhook API"
        ]
      }
    },
    "order_refunded": {
      "post": {
        "summary": "Order refunded",
        "operationId": "orderRefunded",
        "description": "Is called when a confirmed order has been refunded.",
        "tags": [
          "Webhook API"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth": {
        "type": "oauth2",
        "description": "### Making authorized API calls\n\nTo make OAuth requests to the Printful API, `access_token` and `token_type` must be included in the request `Authorization` header.\n\n```\n    # Authorized CURL request example with OAuth\n    curl -X GET 'https://api.printful.com/store/products' \\\n    -H 'Authorization: Bearer smk_GN0I1Os3OdfqzjJnTOWn1wlbqqq2Y2Pc10TS'\n```",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://www.printful.com/oauth/token",
            "tokenUrl": "https://www.printful.com/oauth/token",
            "refreshUrl": "https://www.printful.com/oauth/token",
            "scopes": {
              "orders": "Read and Write access to Orders",
              "orders/read": "Read access to Orders",
              "stores_list": "Read and Write access to Stores",
              "stores_list/read": "Read access to Stores",
              "sync_products": "Read and Write access to SyncProducts",
              "sync_products/read": "Read access to SyncProducts",
              "file_library": "Read and Write access to File library",
              "file_library/read": "Read access to File library",
              "webhooks": "Read and Write access to Webhooks",
              "webhooks/read": "Read access to Webhooks"
            }
          }
        }
      }
    }
  }
}